/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ProductAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ProductStatus } from './productStatus';

export interface Product {
  description?: string;
  id?: number;
  image?: string;
  memory?: string;
  model?: string;
  quantity?: number;
  status?: ProductStatus;
  systemOnChip?: string;
}
