/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ProductAPI
 * OpenAPI spec version: 1.0.0
 */

export type ProductStatus = typeof ProductStatus[keyof typeof ProductStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductStatus = {
  INSTOCK: 'INSTOCK',
  LOWSTOCK: 'LOWSTOCK',
  OUTOFSTOCK: 'OUTOFSTOCK',
} as const;
